import { Link } from "@chakra-ui/react"
const privacyPolicyList = [{
    title: 'Terms of use of Agreement',
    para: 'These Terms Of Use are a legal agreement (“Agreement”) between you (“User”) and AppBroda Tech. Fzco., a UAE registered company (“AB”). By accessing the AB web site, currently located at http://3.7.216.29(the “Site”) and using any of the Services (as defined below) accessible through the Site, you become a User and agree to, and are bound by, the terms and conditions of this Agreement and Privacy Policy for as long as you continue to use the Site or Services. IF YOU DO NOT AGREE TO BE BOUND BY THIS AGREEMENT, DO NOT USE THE SITE OR THE SERVICES. Your use of, or participation in, certain Services may be subject to additional terms, and such terms will be either listed in this Agreement or will be presented to you for your acceptance when you sign up to use such Services. This Agreement is void where prohibited by law, and the right to access the Site is revoked in such jurisdictions.AB is a SaaS platform to help enable the purchase and sale of mobile advertisements (collectively, the “Services”). AB may offer additional services or revise any of the Services, at its discretion, and the right to cease offering any of the Services.'
},
{
    title: '1. Eligibility',
    para: 'Minimum Age.You must be an individual person, at least 18 years old to use the Site and to register for the Services. By using the Services, you represent and warrant that you are at least 18 years old'
},{
    title: '2. Use of Site and Service',
    bulletPoints: ['Exclusive Use – Your account is for your personal use only. You may not authorize others to use your account, and you may not assign or otherwise transfer your account to any other person or entity. You acknowledge that AB is not responsible for third party access to your account that results from theft or misappropriation of your user names and passwords. AB may assign this Agreement in whole or in part at any time without your consent','Geographic Limitations – The Site and Services are intended for use in worldwide. You will only use the Services in a manner consistent with this Agreement and any and all applicable local, state, national and international laws and regulations. Registration for, and use of, the Services are void where prohibited. To the extent that the Services are not legal in your jurisdiction, you may not use the Services. The Services may not be used where prohibited by law.','Risk Assumption and Precautions – AB is not responsible for the conduct, whether online or offline, of any User of the Site or of the Service. AB is not responsible for any problems or technical malfunction of any telephone network or lines, computer online systems, servers or providers, computer equipment, software, failure of email or players on account of technical problems or traffic congestion on the Internet or at any site or combination thereof, including injury or damage to Users’ or to any other person’s computer related to or resulting from participating or downloading materials in connection with the Web and/or in connection with the Service. Under no circumstances will AB or any of its affiliates, advertisers, promoters or distribution partners be responsible for any loss or damage, including personal injury or death, resulting from anyone’s use of the Site or the Services. The Site and the Services are provided “AS-IS” and AB expressly disclaims any warranty of merchantability, fitness for a particular purpose, or non-infringement. You assume all risks when using the Services.','No False Information – You will not provide inaccurate, misleading, or false information to AB. If the information provided to AB subsequently becomes inaccurate, misleading, or false, you will promptly notify AB of such change.','Unique and Bona Fide Profile – As a Registered User of the Service, you will create only one unique profile.','No Harassment of AB Employees or Agents – You will not harass, annoy, intimidate or threaten any AB employees or agents engaged in providing any portion of the Services to you.',
'Publishers – If User is a publisher, User shall not authorize or encourage any third party to generate fraudulent impressions of or fraudulent clicks on any advertisement, including but not limited to, through repeated manual clicks, the use of robots or other automated query tools and/or computer-generated search requests, and/or the fraudulent use of other search engine optimization services and/or software. Users who are publishers may list assets including but not limited to mobile sites, applications, and device platforms (“Mobile Properties”) and make them available for advertisement. Users who are publishers hereby grant AB the right to access, index, store, and cache requests made from User’s mobile websites (“Mobile Property”) to the Services, including by automated means. Users who are publishers allow AB to access publishers’ applications to serve AB’s personalized advertisements. Users who are advertisers may produce content including but not limited to text links, banners, videos, and graphics (“Advertisements”) for display on a publisher’s Mobile Property. User agrees to comply with the technical specifications provided by AB to enable proper display of the Advertisements in connection with the Services.']
    }, {
    title:'3. Disclosure',
    bulletPoints: [<>AppBroda&apos;s use and transfer to any other app of information received from Google APIs will adhere to <Link href='https://developers.google.com/terms/api-services-user-data-policy#additional_requirements_for_specific_api_scopes' target='_blank' color="blue">Google API Services User Data Policy</Link>, including the Limited Use requirements.</>]
}]

export {privacyPolicyList}